# Configuração do Prometheus com SPM

global:
  scrape_interval: 15s # Com que frequência coletar métricas

# Arquivos de regras de alerta
rule_files:
  - "/etc/prometheus/spm-alerts.yml"

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"] # Coleta métricas normais + SPM
    scrape_interval: 10s
    metrics_path: /metrics

  # Job para métricas administrativas do Jaeger
  - job_name: "jaeger-admin"
    static_configs:
      - targets: ["jaeger:14269"] # Admin port do Jaeger
    scrape_interval: 30s
