# Configuração do Prometheus

global:
  scrape_interval: 15s # Com que frequência coletar métricas

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"] # Alvo: o exportador prometheus do nosso collector
