# Configuração do Prometheus com SPM e Alertmanager

global:
  scrape_interval: 15s # Com que frequência coletar métricas

# Configuração do Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Arquivos de regras de alerta
rule_files:
  - "/etc/prometheus/spm-alerts.yml"
  - "/etc/prometheus/fintelli-enhanced-alerts.yml"

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"] # Coleta métricas normais + SPM
    scrape_interval: 10s
    metrics_path: /metrics

  # Job para métricas administrativas do Jaeger
  - job_name: "jaeger-admin"
    static_configs:
      - targets: ["jaeger:14269"] # Admin port do Jaeger
    scrape_interval: 30s

  # Job para métricas do próprio Prometheus
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 30s

  # Job para métricas do Alertmanager
  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]
    scrape_interval: 30s
